### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Nannaan** [Nannaan/protospace-39306#2]
#URL
https://protospace-39306.onrender.com

**Comment by shodai-ito** [comment]
@Nannaan さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること**
画像は問題ありませんでしたが、プロトタイプ名をクリックしても、該当するプロトタイプの詳細画面へ遷移できませんでした。
プロトタイプ名でも詳細ページに遷移できるよう実装をお願いします！

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Nannaan** [comment]
・プロトタイプ名をクリックすると該当するプロトタイプの詳細画面に遷移する
こちらの箇所を修正しました。

また本番環境で確認していたところ、画像が表示されなくなってしまったのですが問題ないでしょうか？（私の画面だけで起きている現象？）他はイジってはいないはずなんですが…！
https://gyazo.com/5a5b39f78114abe1a8dfea675debcb33

ご確認よろしくお願いいたします！

**Comment by shodai-ito** [comment]
@Nannaan さん、再度ご提出ありがとうございます‼︎
画像が表示されないとのことですが、現段階では仕様ですので問題ありません！

挙動確認を行ったところ、正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
